// Generated by ReScript, PLEASE EDIT WITH CARE


var plusButton = document.getElementById("plus-one");

var minusButton = document.getElementById("minus-one");

var countElement = document.getElementById("count");

window.count = 0;

function renderCountTextView(count) {
  countElement.innerText = count === 0 ? "Count is zero" : "Count is " + String(count);
  
}

function updateCount(steps) {
  window.count = steps + window.count | 0;
  
}

function updateCountClass(count) {
  countElement.className = "count" + (
    count > 0 ? " count-positive" : (
        count < 0 ? " count-negative" : " count-zero"
      )
  );
  
}

function renderView(steps) {
  updateCount(steps);
  renderCountTextView(window.count);
  return updateCountClass(window.count);
}

function minusOne(param) {
  return renderView(-1);
}

function plusOne(param) {
  return renderView(1);
}

plusButton.addEventListener("click", plusOne);

minusButton.addEventListener("click", minusOne);

export {
  plusButton ,
  minusButton ,
  countElement ,
  renderCountTextView ,
  updateCount ,
  updateCountClass ,
  renderView ,
  minusOne ,
  plusOne ,
  
}
/* plusButton Not a pure module */
