// Generated by ReScript, PLEASE EDIT WITH CARE


var plusButton = document.getElementById("plus-one");

var minusButton = document.getElementById("minus-one");

var countElement = document.getElementById("count");

var count = {
  contents: 0
};

function renderCountTextView(param) {
  var n = count.contents;
  countElement.innerText = n === 0 ? "Count is zero" : "Count is " + String(n);
  
}

function updateCount(steps) {
  count.contents = count.contents + steps | 0;
  
}

function updateCountClass(param) {
  var n = count.contents;
  countElement.className = "count" + (
    n > 0 ? " count-positive" : (
        n < 0 ? " count-negative" : " count-zero"
      )
  );
  
}

function renderView(steps) {
  updateCount(steps);
  renderCountTextView(undefined);
  return updateCountClass(undefined);
}

function minusOne(param) {
  return renderView(-1);
}

function plusOne(param) {
  return renderView(1);
}

plusButton.addEventListener("click", plusOne);

minusButton.addEventListener("click", minusOne);

export {
  plusButton ,
  minusButton ,
  countElement ,
  count ,
  renderCountTextView ,
  updateCount ,
  updateCountClass ,
  renderView ,
  minusOne ,
  plusOne ,
  
}
/* plusButton Not a pure module */
